- name: Install redis
  ansible.builtin.dnf:
    name: '@redis:7'
    state: present
- name: replace string from redis.conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0
- name: replace password protected from Yes to no
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: protected-mode yes
    replace: protected-mode no
- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: restarted
    name: redis
    enabled: true
