- name: Install nginx
  ansible.builtin.dnf:
    name: '@nginx:1.24'
    state: present
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: Copy file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true





