- name: mySQL installtion
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true

- name: change default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1


