- name: Import NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodeJS

- name: Copy MongoRepo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.harshitsompura.online </app/db/master-data.js
- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: restarted
    name: catalogue
    enabled: true
    daemon-reload: true


