- name: Add the user roboshop
  ansible.builtin.user:
    name: roboshop
- name: Recursively remove directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: Recursively create directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /app
    remote_src: yes
