- name: Copy Service file file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{ component }}"
    enabled: true
    daemon-reload: true
